import streamlit as st
import numpy as np
import pandas as pd
import joblib
import os


st.set_page_config(
    page_title="CryptoPredict | Bitcoin Analytics",
    page_icon="",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for Professional Styling
st.markdown("""
    <style>
    .main-header {
        font-size: 2.2rem;
        font-weight: 700;
        color: #F7931A;
        margin-bottom: 0.2rem;
    }
    .sub-header {
        font-size: 1rem;
        color: #A0A0A0;
        margin-bottom: 2rem;
    }
    .metric-card {
        background-color: #1E222D;
        border-radius: 10px;
        padding: 15px;
        border: 1px solid #2A2E39;
    }
    </style>
""", unsafe_allow_html=True)

# 2. Sidebar Navigation & Info
with st.sidebar:
    st.image("https://cryptologos.cc/logos/bitcoin-btc-logo.png", width=60)
    st.title("CryptoPredict AI")
    st.write("Professional Bitcoin Price Prediction Tool powered by Machine Learning.")
    
    st.divider()
    
    st.markdown("###  Instructions")
    st.caption("1. Enter the latest **Open, High, Low, Close, and Volume** data.")
    st.caption("2. Click **Generate Prediction** to analyze.")
    st.caption("3. Review predicted metrics for upcoming trading sessions.")
    
    st.divider()
    st.warning(" **Disclaimer:** Market predictions are generated by AI models and should not be considered financial advice.")

# Header Section
st.markdown('<div class="main-header"> Bitcoin Price Prediction Dashboard</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Input current market metrics to forecast the next closing price.</div>', unsafe_allow_html=True)

# Load Model
model_path = os.path.join(os.path.dirname(__file__), 'btc_model.pkl')

@st.cache_resource
def load_btc_model():
    if os.path.exists('btc_model.pkl'):
        return joblib.load('btc_model.pkl')
    elif os.path.exists(model_path):
        return joblib.load(model_path)
    else:
        raise FileNotFoundError("Model file 'btc_model.pkl' not found.")

try:
    model = load_btc_model()
    
    # Input Layout in 2 Columns
    col_input, col_chart = st.columns([1, 1], gap="large")
    
    with col_input:
        st.subheader(" Market Input Data")
        
        c1, c2 = st.columns(2)
        with c1:
            open_price = st.number_input("Open Price ($)", value=60000.0, step=100.0)
            high_price = st.number_input("High Price ($)", value=61000.0, step=100.0)
            low_price  = st.number_input("Low Price ($)", value=59000.0, step=100.0)
            
        with c2:
            close_price = st.number_input("Close Price ($)", value=60500.0, step=100.0)
            volume      = st.number_input("24h Volume ($)", value=30000000000.0, step=1000000.0)

        # Technical Calculations
        calc_return = (close_price - open_price) / open_price if open_price != 0 else 0.0
        calc_ma7    = close_price
        calc_ma21   = close_price
        calc_rsi    = 50.0

        st.markdown("<br>", unsafe_allow_html=True)
        predict_btn = st.button(" Forecast Next Price", type="primary", use_container_width=True)

    with col_chart:
        st.subheader(" Quick Overview")
        # Visualizing simple high/low range
        chart_data = pd.DataFrame({
            "Metric": ["Low", "Open", "Close", "High"],
            "Price ($)": [low_price, open_price, close_price, high_price]
        })
        st.bar_chart(chart_data.set_index("Metric"))

    # Results Section
    if predict_btn:
        features = np.array([[open_price, high_price, low_price, close_price, volume, 
                              calc_return, calc_ma7, calc_ma21, calc_rsi]])
        
        prediction = model.predict(features)[0]
        price_diff = prediction - close_price
        pct_change = (price_diff / close_price) * 100

        st.divider()
        st.subheader(" Prediction Result")
        
        m1, m2, m3 = st.columns(3)
        
        m1.metric(
            label="Target Forecast Price",
            value=f"${prediction:,.2f}",
            delta=f"{price_diff:+,.2f} ({pct_change:+.2f}%)"
        )
        
        m2.metric(
            label="Current Input Close",
            value=f"${close_price:,.2f}"
        )
        
        m3.metric(
            label="Market Sentiment",
            value="Bullish " if price_diff > 0 else "Bearish "
        )

except Exception as e:
    st.error(f"Error loading model: {e}")
