import streamlit as st
import numpy as np
import pandas as pd
import joblib
import os
import yfinance as yf

# 1. Page Configuration
st.set_page_config(
    page_title="CryptoPredict AI | Multi-Horizon Forecast",
    page_icon="",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
    <style>
    .main-header { font-size: 2.2rem; font-weight: 700; color: #F7931A; margin-bottom: 0.2rem; }
    .sub-header { font-size: 1rem; color: #A0A0A0; margin-bottom: 1.5rem; }
    </style>
""", unsafe_allow_html=True)

# 2. Sidebar Navigation & Info
with st.sidebar:
    st.image("https://cryptologos.cc/logos/bitcoin-btc-logo.png", width=60)
    st.title("CryptoPredict AI")
    st.write("Automated Live Bitcoin Analytics & Multi-Horizon AI Forecasting.")
    
    st.divider()
    
    st.markdown("###  Forecast Settings")
    # Timeframe selection dropdown
    forecast_horizon = st.selectbox(
        "Select Prediction Period:",
        options=["Tomorrow (1 Day)", "Next Week (7 Days)", "Next Month (30 Days)"]
    )
    
    st.divider()
    st.warning(" **Disclaimer:** Market predictions are generated by AI models and should not be considered financial advice.")

# Header
st.markdown('<div class="main-header"> Bitcoin Live Market & Future Prediction</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Real-time market analytics with Daily, Weekly, and Monthly AI Forecast Graphs.</div>', unsafe_allow_html=True)

# Load Model
model_path = os.path.join(os.path.dirname(__file__), 'btc_model.pkl')

@st.cache_resource
def load_btc_model():
    if os.path.exists('btc_model.pkl'):
        return joblib.load('btc_model.pkl')
    elif os.path.exists(model_path):
        return joblib.load(model_path)
    else:
        raise FileNotFoundError("Model file 'btc_model.pkl' not found.")

# Fetch Live Data
@st.cache_data(ttl=300)
def get_live_btc_data():
    ticker = yf.Ticker("BTC-USD")
    df = ticker.history(period="30d")
    return df

try:
    model = load_btc_model()
    df_live = get_live_btc_data()
    
    if len(df_live) >= 2:
        today_data = df_live.iloc[-1]
        yesterday_data = df_live.iloc[-2]
        
        # Calculate daily change
        price_change = today_data['Close'] - yesterday_data['Close']
        pct_change = (price_change / yesterday_data['Close']) * 100
        
        # Display Live Overview Cards
        st.subheader(" Live Bitcoin Market Overview")
        m1, m2, m3, m4, m5 = st.columns(5)
        
        m1.metric("Current / Today Close", f"${today_data['Close']:,.2f}", f"{price_change:+,.2f} ({pct_change:+.2f}%)")
        m2.metric("Today High", f"${today_data['High']:,.2f}")
        m3.metric("Today Low", f"${today_data['Low']:,.2f}")
        m4.metric("Today Open", f"${today_data['Open']:,.2f}")
        m5.metric("24h Volume", f"{today_data['Volume']:,.0f}")
        
        st.divider()
        
        # Layout for Controls & Prediction Button
        col_input, col_chart = st.columns([1, 1], gap="large")
        
        with col_input:
            st.subheader(" Current Base Parameters")
            
            open_price = st.number_input("Open Price ($)", value=float(today_data['Open']), step=100.0)
            high_price = st.number_input("High Price ($)", value=float(today_data['High']), step=100.0)
            low_price  = st.number_input("Low Price ($)", value=float(today_data['Low']), step=100.0)
            close_price = st.number_input("Close Price ($)", value=float(today_data['Close']), step=100.0)
            volume      = st.number_input("24h Volume", value=float(today_data['Volume']), step=1000000.0)

            st.markdown("<br>", unsafe_allow_html=True)
            predict_btn = st.button(f" Generate Forecast ({forecast_horizon})", type="primary", use_container_width=True)

        with col_chart:
            st.subheader(" Historical 30-Day Trend")
            st.line_chart(df_live['Close'])

        # Multi-Horizon Prediction Logic & Graph
        if predict_btn:
            # Determine days to predict
            if "1 Day" in forecast_horizon:
                days_to_predict = 1
            elif "7 Days" in forecast_horizon:
                days_to_predict = 7
            else:
                days_to_predict = 30
            
            # Recursive Prediction for multi-day forecasting
            predicted_prices = []
            curr_open = open_price
            curr_high = high_price
            curr_low = low_price
            curr_close = close_price
            curr_vol = volume

            for _ in range(days_to_predict):
                calc_return = (curr_close - curr_open) / curr_open if curr_open != 0 else 0.0
                calc_ma7 = curr_close
                calc_ma21 = curr_close
                calc_rsi = 50.0

                features = np.array([[curr_open, curr_high, curr_low, curr_close, curr_vol,
                                      calc_return, calc_ma7, calc_ma21, calc_rsi]])
                
                next_pred = model.predict(features)[0]
                predicted_prices.append(next_pred)

                # Update baseline for next recursive step
                curr_open = curr_close
                curr_close = next_pred
                curr_high = max(curr_high, next_pred)
                curr_low = min(curr_low, next_pred)

            # Generate Future Dates
            last_date = df_live.index[-1]
            future_dates = [last_date + pd.Timedelta(days=i+1) for i in range(days_to_predict)]

            forecast_df = pd.DataFrame({
                "Date": future_dates,
                "Predicted Close ($)": predicted_prices
            }).set_index("Date")

            st.divider()
            st.subheader(f" AI Prediction Graph ({forecast_horizon})")

            # Metrics
            final_pred = predicted_prices[-1]
            total_diff = final_pred - close_price
            total_pct = (total_diff / close_price) * 100

            r1, r2, r3 = st.columns(3)
            r1.metric("Final Projected Price", f"${final_pred:,.2f}", f"{total_diff:+,.2f} ({total_pct:+.2f}%)")
            r2.metric("Current Starting Price", f"${close_price:,.2f}")
            r3.metric("Overall Horizon Trend", "Bullish " if total_diff > 0 else "Bearish ")

            # Display Forecast Graph
            st.line_chart(forecast_df)
            
            # Table Breakdown
            with st.expander(" View Daily Forecast Breakdown Table"):
                st.dataframe(forecast_df.style.format("${:,.2f}"))

except Exception as e:
    st.error(f"Error executing app: {e}")
