import streamlit as st
import numpy as np
import pandas as pd
import joblib
import os
import yfinance as yf

# 1. Page Configuration
st.set_page_config(
    page_title="CryptoPredict AI | Live Bitcoin Analytics",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
    <style>
    .main-header {
        font-size: 2.2rem;
        font-weight: 700;
        color: #F7931A;
        margin-bottom: 0.2rem;
    }
    .sub-header {
        font-size: 1rem;
        color: #A0A0A0;
        margin-bottom: 1.5rem;
    }
    </style>
""", unsafe_allow_html=True)

# 2. Sidebar Navigation & Info
with st.sidebar:
    st.image("https://cryptologos.cc/logos/bitcoin-btc-logo.png", width=60)
    st.title("CryptoPredict AI")
    st.write("Automated Live Bitcoin Analytics & Tomorrow's Price Forecast.")
    
    st.divider()
    
    st.markdown("### 📌 How It Works")
    st.caption("1. Live market data is fetched automatically via Yahoo Finance.")
    st.caption("2. Review yesterday's and today's Bitcoin performance.")
    st.caption("3. Click **Forecast Tomorrow's Price** to run the ML model.")
    
    st.divider()
    st.warning("⚠️ **Disclaimer:** Market predictions are generated by AI models and should not be considered financial advice.")

# Header
st.markdown('<div class="main-header">⚡ Bitcoin Live Market & Price Prediction</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Automated real-time Bitcoin price fetching & AI-powered next-day forecasting.</div>', unsafe_allow_html=True)

# Load Model
model_path = os.path.join(os.path.dirname(__file__), 'btc_model.pkl')

@st.cache_resource
def load_btc_model():
    if os.path.exists('btc_model.pkl'):
        return joblib.load('btc_model.pkl')
    elif os.path.exists(model_path):
        return joblib.load(model_path)
    else:
        raise FileNotFoundError("Model file 'btc_model.pkl' not found.")

# Fetch Live Data
@st.cache_data(ttl=300)
def get_live_btc_data():
    ticker = yf.Ticker("BTC-USD")
    df = ticker.history(period="7d")
    return df

try:
    model = load_btc_model()
    df_live = get_live_btc_data()
    
    if len(df_live) >= 2:
        today_data = df_live.iloc[-1]
        yesterday_data = df_live.iloc[-2]
        
        # Calculate daily change
        price_change = today_data['Close'] - yesterday_data['Close']
        pct_change = (price_change / yesterday_data['Close']) * 100
        
        # Display Live Overview Cards
        st.subheader("📊 Live Bitcoin Market Overview (Auto-Fetched)")
        m1, m2, m3, m4, m5 = st.columns(5)
        
        m1.metric("Current / Today Close", f"${today_data['Close']:,.2f}", f"{price_change:+,.2f} ({pct_change:+.2f}%)")
        m2.metric("Today High", f"${today_data['High']:,.2f}")
        m3.metric("Today Low", f"${today_data['Low']:,.2f}")
        m4.metric("Today Open", f"${today_data['Open']:,.2f}")
        m5.metric("24h Volume", f"{today_data['Volume']:,.0f}")
        
        st.divider()
        
        # Layout for Inputs & Chart
        col_input, col_chart = st.columns([1, 1], gap="large")
        
        with col_input:
            st.subheader("⚙️ Market Parameters for Prediction")
            st.info("Values are auto-filled with current market data, but you can adjust them manually if needed.")
            
            open_price = st.number_input("Open Price ($)", value=float(today_data['Open']), step=100.0)
            high_price = st.number_input("High Price ($)", value=float(today_data['High']), step=100.0)
            low_price  = st.number_input("Low Price ($)", value=float(today_data['Low']), step=100.0)
            close_price = st.number_input("Close Price ($)", value=float(today_data['Close']), step=100.0)
            volume      = st.number_input("24h Volume", value=float(today_data['Volume']), step=1000000.0)
            
            # Auto-calculated technical indicators
            calc_return = (close_price - open_price) / open_price if open_price != 0 else 0.0
            calc_ma7    = close_price
            calc_ma21   = close_price
            calc_rsi    = 50.0

            st.markdown("<br>", unsafe_allow_html=True)
            predict_btn = st.button("🔮 Forecast Tomorrow's Price", type="primary", use_container_width=True)

        with col_chart:
            st.subheader("📈 Recent 7-Day Trend")
            st.line_chart(df_live['Close'])

        # Prediction Result
        if predict_btn:
            features = np.array([[open_price, high_price, low_price, close_price, volume, 
                                  calc_return, calc_ma7, calc_ma21, calc_rsi]])
            
            prediction = model.predict(features)[0]
            pred_diff = prediction - close_price
            pred_pct = (pred_diff / close_price) * 100

            st.divider()
            st.subheader("🎯 Tomorrow's Forecast Result")
            
            r1, r2, r3 = st.columns(3)
            
            r1.metric(
                label="Predicted Close Price (Tomorrow)",
                value=f"${prediction:,.2f}",
                delta=f"{pred_diff:+,.2f} ({pred_pct:+.2f}%)"
            )
            
            r2.metric(
                label="Baseline Input Close",
                value=f"${close_price:,.2f}"
            )
            
            r3.metric(
                label="Expected Sentiment",
                value="Bullish 📈" if pred_diff > 0 else "Bearish 📉"
            )
            
    else:
        st.error("Unable to fetch live market data at the moment. Please try again later.")

except Exception as e:
    st.error(f"Error executing app: {e}")
